.TH docmail "1" "0.7.0" "scan, ocr and mail documents to yourself"

.SH NAME
docmail \- micro email document manager

.SH SYNOPSIS
\fBdocmail\fR [-h] [-n NUMSCANS] [-s SUBJECT] [-t RECEIVER] [-p PASSWORD] [-l LANG] [-r RES] [-m MODE] [-v VERSION] [file [file ...]]\fR

.SH DESCRIPTION
docmail is a micro document management system. It will scan your documents with your default sane scanner (or takes them as files), do an OCR and eMail them to yourself.

.SH OPTIONS
.IP "\fB\-\-dotmatrix\fR" 4
Use recognition mode optimized for text printed with a dot matrix printer.

.IP "\fB\-n, --numScans\fR" 4
number of pages to scan with your default sane scanner

.IP "\fB\files \fR \fIfilenames\fR" 4
one or more files to OCR and eMail; Use \'scan\' to insert a scan with your default sane scanner

.IP "\fB\-s --subject\fR" 4
subject of the eMail

.IP "\fB\-t --to\fR" 4
eMail-adress to send the eMail to (overrides config file)

.IP "\fB\-p --password
mailserver-password
type \'?\' to be asked on the command line (hidden)
if none given i\'ll try to login without authentication

.IP "\fB\-l --language\fR" 4
By default docmail recognizes the languages specified in the config file. To change the language use the command line switch \fB\-l\fR followed by a language code (an ISO 639-2 three-letter code). Check the man-page of tesseract to get a list of supported languages.

.IP "\fB\-r --resolution\fR" 4
scan resolution; default: 300

.IP "\fB\-m --colormode\fR" 4
scanner color mode; default: Gray, Options: Lineart, Gray, Color

.IP "\fB\-b --brightness\fR" 4
scanner brightness; default: -50, Options: -100..100

.IP "\fB\-c --contrast\fR" 4
scanner contrast; default: 100 (to keep the file size small), Options: -100..100

.IP "\fB\-v --version\fR" 4
print the version number of docmail and exit

.SH HOMEPAGE
More information about cuneiform can be found at <\fIhttp://polarwinkel.de/\fR>.

.SH AUTHOR
cuneiform was written by Dirk Winkel <\fIit@polarwinkel.de\fR>.
